// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Datos.Migrations
{
    [DbContext(typeof(TiendaReparacionContext))]
    partial class TiendaReparacionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmpleadoModelTareaModel", b =>
                {
                    b.Property<int>("EmpleadosEmpleadoID")
                        .HasColumnType("int");

                    b.Property<int>("TareasTareaID")
                        .HasColumnType("int");

                    b.HasKey("EmpleadosEmpleadoID", "TareasTareaID");

                    b.HasIndex("TareasTareaID");

                    b.ToTable("EmpleadoModelTareaModel");
                });

            modelBuilder.Entity("EmpleadoModelTrabajoModel", b =>
                {
                    b.Property<int>("EmpleadosEmpleadoID")
                        .HasColumnType("int");

                    b.Property<int>("TrabajosTrabajoID")
                        .HasColumnType("int");

                    b.HasKey("EmpleadosEmpleadoID", "TrabajosTrabajoID");

                    b.HasIndex("TrabajosTrabajoID");

                    b.ToTable("EmpleadoModelTrabajoModel");
                });

            modelBuilder.Entity("Modelos.ClienteModel", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Modelos.EmpleadoModel", b =>
                {
                    b.Property<int>("EmpleadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoID");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Modelos.PrecioTareaModel", b =>
                {
                    b.Property<int>("PrecioTareaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrecioTareaID"));

                    b.Property<DateTime>("FechaVigencia")
                        .HasColumnType("datetime2");

                    b.Property<float>("Monto")
                        .HasColumnType("real");

                    b.Property<int>("TareaID")
                        .HasColumnType("int");

                    b.HasKey("PrecioTareaID");

                    b.HasIndex("TareaID");

                    b.ToTable("PreciosTarea");
                });

            modelBuilder.Entity("Modelos.TareaModel", b =>
                {
                    b.Property<int>("TareaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaID"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TareaID");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Modelos.TrabajoModel", b =>
                {
                    b.Property<int>("TrabajoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrabajoID"));

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionProblema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreDispositivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrabajoID");

                    b.HasIndex("ClienteID");

                    b.ToTable("Trabajos");
                });

            modelBuilder.Entity("TareaModelTrabajoModel", b =>
                {
                    b.Property<int>("TareasTareaID")
                        .HasColumnType("int");

                    b.Property<int>("TrabajosTrabajoID")
                        .HasColumnType("int");

                    b.HasKey("TareasTareaID", "TrabajosTrabajoID");

                    b.HasIndex("TrabajosTrabajoID");

                    b.ToTable("TareaModelTrabajoModel");
                });

            modelBuilder.Entity("EmpleadoModelTareaModel", b =>
                {
                    b.HasOne("Modelos.EmpleadoModel", null)
                        .WithMany()
                        .HasForeignKey("EmpleadosEmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.TareaModel", null)
                        .WithMany()
                        .HasForeignKey("TareasTareaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmpleadoModelTrabajoModel", b =>
                {
                    b.HasOne("Modelos.EmpleadoModel", null)
                        .WithMany()
                        .HasForeignKey("EmpleadosEmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.TrabajoModel", null)
                        .WithMany()
                        .HasForeignKey("TrabajosTrabajoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modelos.PrecioTareaModel", b =>
                {
                    b.HasOne("Modelos.TareaModel", "Tarea")
                        .WithMany("PreciosTarea")
                        .HasForeignKey("TareaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("Modelos.TrabajoModel", b =>
                {
                    b.HasOne("Modelos.ClienteModel", "Cliente")
                        .WithMany("Trabajos")
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TareaModelTrabajoModel", b =>
                {
                    b.HasOne("Modelos.TareaModel", null)
                        .WithMany()
                        .HasForeignKey("TareasTareaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.TrabajoModel", null)
                        .WithMany()
                        .HasForeignKey("TrabajosTrabajoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modelos.ClienteModel", b =>
                {
                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("Modelos.TareaModel", b =>
                {
                    b.Navigation("PreciosTarea");
                });
#pragma warning restore 612, 618
        }
    }
}
